### ISSUE TITLE
Question: Any beginner tutorials?

### ISSUE THREAD

**Issue by thejimbirch** [kalamuna/kss-bootstrap#39]
Hi,

Any beginner tutorials on getting this set up?  I tried to follow the read me, but could not get it to run with out error.

Thanks,
Jim

**Comment by RobLoach** [comment]
What error do you get?

**Comment by thejimbirch** [comment]
kss-node bootstrap docroot/styleguide -t bootstrap
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/Jim/vagrant/xmd8/bootstrap/index.html'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at kssHandlebarsGenerator.init (/usr/local/lib/node_modules/kss/generator/handlebars/kss_handlebars_generator.js:137:22)
    at cli (/usr/local/lib/node_modules/kss/lib/cli.js:171:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/kss/bin/kss-node:9:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by RobLoach** [comment]
`-t bootstrap`, the `bootstrap` should likely point to `node_modules/kss-bootstrap/bootstrap`.

**Comment by RobLoach** [comment]
Yeah, the Builder itself is very old, doesn't work on 3.0. I'm going to update this story to be "Support KSS 3.x"
